(************************************************)
(*       AUTOGENERATED FILE - DO NOT EDIT!      *)
(************************************************)
(* Generated by: ocaml-protoc-plugin            *)
(* https://github.com/issuu/ocaml-protoc-plugin *)
(************************************************)
(*
  Source: google/protobuf/source_context.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot='[@@deriving sexp_of]'
    opens=[Core]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
*)

open Ocaml_protoc_plugin.Runtime [@@warning "-33"]
open Core [@@warning "-33"]
module Google = struct
  module Protobuf = struct
    module rec SourceContext : sig
      val name': unit -> string
      type t = string [@@deriving sexp_of]
      val make : ?file_name:string -> unit -> t
      val to_proto: t -> Runtime'.Writer.t
      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    end = struct 
      let name' () = "source_context.google.protobuf.SourceContext"
      type t = string[@@deriving sexp_of]
      let make =
        fun ?file_name () -> 
        let file_name = match file_name with Some v -> v | None -> {||} in
        file_name
      
      let to_proto =
        let apply = fun ~f:f' file_name -> f' [] file_name in
        let spec = Runtime'.Serialize.C.( basic (1, string, proto3) ^:: nil ) in
        let serialize = Runtime'.Serialize.serialize [] (spec) in
        fun t -> apply ~f:serialize t
      
      let from_proto =
        let constructor = fun _extensions file_name -> file_name in
        let spec = Runtime'.Deserialize.C.( basic (1, string, proto3) ^:: nil ) in
        let deserialize = Runtime'.Deserialize.deserialize [] spec constructor in
        fun writer -> deserialize writer |> Runtime'.Result.open_error
      
    end
  end
end